/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni/jni.h>
/* Header for class wcrl_configurator_server_smodels_EngineInterface */

#ifndef _Included_wcrl_configurator_server_smodels_EngineInterface
#define _Included_wcrl_configurator_server_smodels_EngineInterface
#ifdef __cplusplus
extern "C" {
#endif
#undef wcrl_configurator_server_smodels_EngineInterface_ID_RESET
#define wcrl_configurator_server_smodels_EngineInterface_ID_RESET -1L
/*
 * Class:     wcrl_configurator_server_smodels_EngineInterface
 * Method:    initModel
 * Signature: (Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_wcrl_configurator_server_smodels_EngineInterface_initModel
  (JNIEnv *, jobject, jstring, jobjectArray, jobjectArray);

/*
 * Class:     wcrl_configurator_server_smodels_EngineInterface
 * Method:    resetComputeStatement
 * Signature: (ILwcrl/configurator/server/smodels/WCRLConfigurationState;[Ljava/lang/String;[Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_wcrl_configurator_server_smodels_EngineInterface_resetComputeStatement
  (JNIEnv *, jobject, jint, jobject, jobjectArray, jobjectArray);

/*
 * Class:     wcrl_configurator_server_smodels_EngineInterface
 * Method:    releaseModel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_wcrl_configurator_server_smodels_EngineInterface_releaseModel
  (JNIEnv *, jobject, jint);

/*
 * Class:     wcrl_configurator_server_smodels_EngineInterface
 * Method:    getConfigurationState
 * Signature: (ILwcrl/configurator/server/smodels/WCRLConfigurationState;)Z
 */
JNIEXPORT jboolean JNICALL Java_wcrl_configurator_server_smodels_EngineInterface_getConfigurationState
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     wcrl_configurator_server_smodels_EngineInterface
 * Method:    findConfiguration
 * Signature: (ILwcrl/configurator/server/smodels/WCRLConfigurationState;)Z
 */
JNIEXPORT jboolean JNICALL Java_wcrl_configurator_server_smodels_EngineInterface_findConfiguration
  (JNIEnv *, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
